from app.config import (
    Settings,
)

settings = Settings()
# generated by running: openssl rand -hex 128
JWT_SECRET_KEY = settings.JWT_SECRET_KEY
JWT_ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 360
